server:
  port: 8084


spring:
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      auto-offset-reset: earliest

management:
  server:
    port: 8094
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

app:
  rest:
    api:
      prefix: /api

kafka:
  topic: RATE_REQUESTS
  group_id: RateRequestsProcessor