---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecb-historical-currency-rate
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecb-historical-currency-rate
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ecb-historical-currency-rate
    spec:
      containers:
        - image: northug/ecb-historical-currency-rate:latest
          name: ecb-historical-currency-rate
          ports:
            - containerPort: 8081
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: currency-rate-config
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8091
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8091
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 10
      imagePullSecrets:
        - name: regcred
