server:
  port: 8081

app:
  cache:
    size: 365
  rest:
    api:
      prefix: /api

ecb:
  url: "https://api.exchangerate.host"

management:
  server:
    port: 8091
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

