---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-rate-telegram-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-rate-telegram-bot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-rate-telegram-bot
    spec:
      containers:
        - image: northug/currency-rate-telegram-bot:latest
          name: currency-rate-telegram-bot
          ports:
            - containerPort: 8082
          imagePullPolicy: Never
          envFrom:
            - configMapRef:
                name: currency-rate-config
            - configMapRef:
                name: currency-rate-config-secret
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/readiness
              port: 8092
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /actuator/health/liveness
              port: 8092
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
            initialDelaySeconds: 10
      imagePullSecrets:
        - name: regcred
