server:
  port: 8082

management:
  server:
    port: 8092
  endpoints:
    enabled-by-default: false
  endpoint:
    health:
      enabled: true
      probes:
        enabled: true

app:
  rest:
    api:
      prefix: /api

telegram:
  bot:
    name: Historical exchange rate for KZT
